<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-editing-panel',
	'deps' => [
		'elementor-v2-editor',
		'elementor-v2-editor-panels',
		'elementor-v2-editor-responsive',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-ui',
		'react',
		'wp-i18n',
	],
];
